"""Add is_verified field to UserModel

Revision ID: 0a552e0deaff
Revises: ae0def1e43c8
Create Date: 2024-08-28 10:22:55.564406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a552e0deaff'
down_revision = 'ae0def1e43c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))

    op.drop_constraint('uq_sellers_email', 'sellers', type_='unique')
    op.create_index(op.f('ix_sellers_email'), 'sellers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_email'), table_name='sellers')
    op.create_unique_constraint('uq_sellers_email', 'sellers', ['email'])
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
