"""Remove username column and add full_name, phoneNumber

Revision ID: 9fefe3b98aea
Revises: 30be4fc3d336
Create Date: 2024-09-23 08:03:27.852784

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9fefe3b98aea'
down_revision = '30be4fc3d336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Modify the 'users' table to remove 'username' and ensure 'full_name' and 'phoneNumber' fields are correct
    op.alter_column('users', 'phoneNumber',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)

    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')

    # Create unique constraints on email and phone number fields
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['phoneNumber'])

    # Remove username column
    op.drop_column('users', 'username')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add the username column back for downgrade
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))

    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)

    # Reverse phone number changes
    op.alter_column('users', 'phoneNumber',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # No other tables are restored as we are only concerned with the 'users' and 'sellers' tables.
    
    # ### end Alembic commands ###
