"""Added preference and profile picture to SellerModel

Revision ID: ae0def1e43c8
Revises: 32fcc179c417
Create Date: 2024-08-15 08:35:04.884962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0def1e43c8'
down_revision = '32fcc179c417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    op.add_column('sellers', sa.Column('preferences', sa.String(length=255), nullable=True))
    # Ensure these fields remain NOT NULL unless there is a specific reason to change them
    op.alter_column('sellers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('sellers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('sellers', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('sellers', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # Drop and recreate the unique constraint on email
    op.drop_constraint('sellers_email_key', 'sellers', type_='unique')
    op.create_unique_constraint('uq_sellers_email', 'sellers', ['email'])
    op.create_index(op.f('ix_sellers_name'), 'sellers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_name'), table_name='sellers')
    op.drop_constraint('uq_sellers_email', 'sellers', type_='unique')
    op.create_unique_constraint('sellers_email_key', 'sellers', ['email'])
    op.alter_column('sellers', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sellers', 'rating',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('sellers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('sellers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('sellers', 'preferences')
    op.drop_column('sellers', 'profile_picture')
    # ### end Alembic commands ###
