"""Generate migration for updated models in auth-service

Revision ID: b761911e4a58
Revises: 6efb0d891ca3
Create Date: 2024-09-06 10:47:11.152658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b761911e4a58'
down_revision = '6efb0d891ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    op.drop_table('user_groups')
    op.drop_index('ix_groups_id', table_name='groups')
    op.drop_table('groups')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'otp_code')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'role')
    op.drop_column('users', 'username')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'language_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_code', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('otp_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_column('users', 'is_admin')
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('groups_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='groups_pkey'),
    sa.UniqueConstraint('name', name='groups_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_groups_id', 'groups', ['id'], unique=False)
    op.create_table('user_groups',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='user_groups_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_groups_user_id_fkey')
    )
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='admins_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='admins_pkey')
    )
    # ### end Alembic commands ###
