"""Added VerificationModel

Revision ID: e26230a4b8e0
Revises: c19401518334
Create Date: 2024-11-09 15:21:51.807919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e26230a4b8e0'
down_revision = 'c19401518334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_otp_codes_sellerId', table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.VARCHAR(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('otp_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sellerId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='otp_codes_pkey')
    )
    op.create_index('ix_otp_codes_sellerId', 'otp_codes', ['sellerId'], unique=False)
    # ### end Alembic commands ###
