"""Increase jwt_token_key length to 36

Revision ID: e5536f684724
Revises: 95b7cc50b9fe
Create Date: 2024-09-06 13:02:28.024518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5536f684724'
down_revision = '95b7cc50b9fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### manually add the command to alter the jwt_token_key column ###
    op.alter_column('users', 'jwt_token_key',
               existing_type=sa.String(length=12),
               type_=sa.String(length=36),
               existing_nullable=True)
    
    # ### keep the rest of the commands generated by Alembic ###
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)


def downgrade():
    # ### manually reverse the column type change ###
    op.alter_column('users', 'jwt_token_key',
               existing_type=sa.String(length=36),
               type_=sa.String(length=12),
               existing_nullable=True)

    # ### keep the rest of the commands generated by Alembic ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'sessions', type_='foreignkey')
