"""Added email column to sellers

Revision ID: e767f257915a
Revises: c32295a09b98
Create Date: 2024-08-10 22:32:14.744573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e767f257915a'
down_revision = 'c32295a09b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('email', sa.String(), nullable=False))
    op.drop_index('ix_sellers_id', table_name='sellers')
    op.create_index(op.f('ix_sellers_id'), 'sellers', ['id'], unique=False)
    op.create_index(op.f('ix_sellers_email'), 'sellers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_email'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_id'), table_name='sellers')
    op.create_index('ix_sellers_id', 'sellers', ['id'], unique=True)
    op.drop_column('sellers', 'email')
    # ### end Alembic commands ###
